// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyxa2veFfkUWHtNkJrMM__X7_KBSRJXr4',
    appId: '1:1027418452344:web:41192d10ca866f01e7988d',
    messagingSenderId: '1027418452344',
    projectId: 'chatapp-475a4',
    authDomain: 'chatapp-475a4.firebaseapp.com',
    storageBucket: 'chatapp-475a4.firebasestorage.app',
    measurementId: 'G-PX6HS34H6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfnDEvtwZmueDdBvZIpS3dV1IauxNswmU',
    appId: '1:1027418452344:android:beaa3aae713569c6e7988d',
    messagingSenderId: '1027418452344',
    projectId: 'chatapp-475a4',
    storageBucket: 'chatapp-475a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_zf9q-xJsyEd7pf3G01SIQC9NAK4dGAs',
    appId: '1:1027418452344:ios:038e80fe1c2cdedde7988d',
    messagingSenderId: '1027418452344',
    projectId: 'chatapp-475a4',
    storageBucket: 'chatapp-475a4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_zf9q-xJsyEd7pf3G01SIQC9NAK4dGAs',
    appId: '1:1027418452344:ios:038e80fe1c2cdedde7988d',
    messagingSenderId: '1027418452344',
    projectId: 'chatapp-475a4',
    storageBucket: 'chatapp-475a4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyxa2veFfkUWHtNkJrMM__X7_KBSRJXr4',
    appId: '1:1027418452344:web:a830743a02369477e7988d',
    messagingSenderId: '1027418452344',
    projectId: 'chatapp-475a4',
    authDomain: 'chatapp-475a4.firebaseapp.com',
    storageBucket: 'chatapp-475a4.firebasestorage.app',
    measurementId: 'G-FKEW5YFWE1',
  );

}